Title: Abisola Abimbola Kobomoje
Logo: 7A28F133-1E0A-40CD-83E5-342B0D316199.jpegDescription
Description: A Data Analyst with 3 years of experience, highly proficient with the use of data analysis tools like Excel, SQL and Power BI
#Show_downloads:
#Google_analytics:
Theme: jeky11-theme-minimal
