title: Abisola Kobomoje
logo: profile.jpg
description: I am a Data Analyst with 3 years of experience transforming raw data into actionable insights. Skilled in SQL, Excel, and Power BI. I specialize in building dynamic dashboards, optimizing data processes, and driving data-informed decisions. Passionate about problem-solving and continuous learning, I enjoy working on projects that uncover trends, improve business performance, and deliver value through data storytelling. 
If you'd like to connect or discuss this project:
**Email:** kobomojeabisola@gmail.com
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
